# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c30b2a64f00650fc59791647ca6d663a41d929c61916e6d9892fb0ea54d3b1fda845520c3b9286608ea2eaaadd37316dd47862bb7c95203c0d36c6739f5c0c22

test:
  secret_key_base: a60ae4334db2da015bfcaff07bf7da12e12e7e3822c63ad7e21e63b03c0ad4afb61ac9bd5ae8ebf31f5598e3a2c871b885ac11e2435e0de46f67adadd1ab97e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
